CREATE TABLE user_word(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    word_id BIGINT REFERENCES words(id),
    learned boolean NOT NULL DEFAULT false,
    repetition_count integer NOT NULL DEFAULT 0,
    added_at timestamp NOT NULL DEFAULT now()
)