CREATE TABLE learning_sessions(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    word_ids BIGINT REFERENCES words(id),
    current_question integer,
    correct_answers integer,
    total_questions integer,
    finished boolean
)